
  
spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
  banner:
    location: classpath:/banner/banner.txt
    
  datasource:
    url: jdbc:mysql://localhost:3306/ias?useSSL=false
    username: root
    password: jp10210159jp
    
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update
     